### ISSUE TITLE
Misclassification of a user

### ISSUE THREAD

**Issue by caniszczyk** [cncf/devstats.archive#222]
See: https://all.devstats.cncf.io/d/56/company-commits-table?orgId=1&var-repogroups=All&var-companies=Nokia&from=now-5y&to=now

See one of Max's contributions:
https://github.com/spiffe/java-spiffe/commit/fbae0043de050535eb1232b25ff6f8049dfa6fb2.patch

I couldn't find developer affiliation data that classifies him working for Nokia, why does he come up as a Nokia contribution?

**Comment by CsatariGergely** [comment]
Thanks @caniszczyk for filing this. I can also add that @maxlambrecht is not working for Nokia.

**Comment by lukaszgryglicki** [comment]
github_users.json defines this user affiliation to Nokia, I don't know why, maybe this is a mistake, in this case, please create a PR on `cncf/gitdm` to fix this.

**Comment by caniszczyk** [comment]
@lukaszgryglicki I don't see them listed in github_users.json or any affiliation file?

**Comment by lukaszgryglicki** [comment]
it's in `github_users.json`, see ```"login": "maxlambrecht"```.

**Comment by lukaszgryglicki** [comment]
This was fixed some time ago, closing.

**Comment by CsatariGergely** [comment]
Sorry, but I had not yet time to fix this, so this is not fixed yet.
