### ISSUE TITLE
Scrolling in dashboards list

### ISSUE THREAD

**Issue by dankohn** [cncf/devstats.archive#60]
Please make the dashboards block as long as the list of dashboards. The scrolling behavior is currently counterintuitive because it sometimes scrolls the page and sometimes scrolls the list of dashboards. Since there's nothing below the list, just have the dashboards scroll with the rest of the window.

**Comment by lukaszgryglicki** [comment]
Added to my list.

**Comment by lukaszgryglicki** [comment]
Done on 17 test projects and 15 prod projects via https://github.com/cncf/devstats/commit/37f656741c5d472cf4051efec622561d29253cf7

**Comment by dankohn** [comment]
It's still broken on https://k8s.devstats.cncf.io/dashboard/db/dashboards?refresh=15m&orgId=1

Try using the scroll wheel while the mouse is over the dashboard list. The list just moves up and down a couple pixels, making it seem stuck.

**Comment by lukaszgryglicki** [comment]
I don't have a mouse with scroll atm. Adjusted height again - this could help. Workin on MacBook.
I'll retest on Monday, I was working on this in the meantime (when data for the new Vitess project is generating).

**Comment by dankohn** [comment]
Turn on two finger scrolling on your MacBook track pad to test.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by lukaszgryglicki** [comment]
Tested now on MacBook and an iMac (which has a mouse with the scroll) - I think it is OK now (made a bit more place for dashboards list on k8s.cncftest.io and k8s.devstats.cncf.io).
I think it is fixed now.

**Comment by lukaszgryglicki** [comment]
Closing this, please reopen if still happens.

**Comment by dankohn** [comment]
https://k8s.devstats.cncf.io/dashboard/db/dashboards?refresh=15m&orgId=1

No, it is not resolved. Scroll halfway down. Move the mouse so it's over All Kubernetes Dashboards. Scrolling up and down causes that block to wiggle but doesn't move the main window.

I can do a screenshare if necessary to show you.

**Comment by lukaszgryglicki** [comment]
OK, I can see it, but only when the mouse is exactly over the inner scroll - anyway - investigating.

**Comment by lukaszgryglicki** [comment]
Hmm, it only moves a bit, no matter how big the dashboard list is.
There aren't many options to configure this dashboard...
No idea what to do currently - seems like a bug?

**Comment by lukaszgryglicki** [comment]
It seems like Grafana V5 prerelease bug.
I've made the dashboards list a lot bigger than all dashboards, and it still "captures" the mouse scroll and disallows to scroll entire page.
It should have a vertical scroll bar at all in this case IMHO.
I'll open issue on Grafana.

**Comment by lukaszgryglicki** [comment]
Issue created on Grafana repo: https://github.com/grafana/grafana/issues/10772

**Comment by lukaszgryglicki** [comment]
Fixed by updating Grafana to `grafana_5.0.0-11639beta1`, closing.
